<?php

namespace CoreBundle\Repository;

/**
 * GlassesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GlassesRepository extends \Doctrine\ORM\EntityRepository
{
}
